In [ ]:
#Creating the dataframe

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4)),pd.Series(np.random.rand(4))])
df

          0         1         2         3
0  0.959168  0.584377  0.339422  0.124308
1  0.205907  0.704260  0.393845  0.733996
2  0.461974  0.578807  0.466589  0.984190
3  0.652393  0.712837  0.921830  0.339444

In [ ]:
#Renaming the columns in df.

In [ ]:
df.columns = ['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.959168        0.584377        0.339422        0.124308
1        0.205907        0.704260        0.393845        0.733996
2        0.461974        0.578807        0.466589        0.984190
3        0.652393        0.712837        0.921830        0.339444

In [ ]:
#Descriptive statistics of DF

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.569861        0.645070        0.530422        0.545485
std          0.317528        0.073417        0.266088        0.386368
min          0.205907        0.578807        0.339422        0.124308
25%          0.397958        0.582984        0.380239        0.285660
50%          0.557184        0.644318        0.430217        0.536720
75%          0.729087        0.706404        0.580399        0.796544
max          0.959168        0.712837        0.921830        0.984190

In [ ]:
df.describe(include='all')

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.569861        0.645070        0.530422        0.545485
std          0.317528        0.073417        0.266088        0.386368
min          0.205907        0.578807        0.339422        0.124308
25%          0.397958        0.582984        0.380239        0.285660
50%          0.557184        0.644318        0.430217        0.536720
75%          0.729087        0.706404        0.580399        0.796544
max          0.959168        0.712837        0.921830        0.984190

In [ ]:
#Checking for null values

In [ ]:
df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
#Display of Random value 2 & Ramdom value 3 using Location and index method

In [ ]:
df.loc[0:,'Random value 1	':'Random value 3	']

   Random value 2  Random value 3
0        0.584377        0.339422
1        0.704260        0.393845
2        0.578807        0.466589
3        0.712837        0.921830

In [ ]:
df.iloc[0:,1:3]

   Random value 2  Random value 3
0        0.584377        0.339422
1        0.704260        0.393845
2        0.578807        0.466589
3        0.712837        0.921830